-- =====================================================
-- TAECKER 문의하기 (inquiries)
-- 주의: 이 파일은 실제 운영 DB에 이미 적용되어 있던 내용을
--       소급 기록한 것입니다 (마이그레이션 이력 누락 백필).
--       idempotent(중복 실행 안전)하게 작성했습니다.
-- =====================================================

create table if not exists public.inquiries(
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    content text not null,
    status text not null default 'pending',
    admin_reply text,
    created_at timestamptz not null default now(),
    replied_at timestamptz,
    replied_by uuid references auth.users(id)
);

alter table public.inquiries enable row level security;

drop policy if exists inquiries_insert_own on public.inquiries;
drop policy if exists inquiries_select_own on public.inquiries;
drop policy if exists inquiries_select_admin on public.inquiries;
drop policy if exists inquiries_update_admin on public.inquiries;

-- 본인 명의로만 문의 접수 가능, 정지된 계정은 문의 접수 불가(신고/게시글과 동일 규칙)
create policy inquiries_insert_own
    on public.inquiries
    for insert
    with check (auth.uid() = user_id and not is_suspended());

-- 본인이 접수한 문의는 본인이 조회 가능 (답변 확인용)
create policy inquiries_select_own
    on public.inquiries
    for select
    using (auth.uid() = user_id);

-- 관리자는 전체 문의 조회 가능
create policy inquiries_select_admin
    on public.inquiries
    for select
    using (is_admin_user());

-- 관리자만 답변/상태 변경 가능
create policy inquiries_update_admin
    on public.inquiries
    for update
    using (is_admin_user());
